ALTER TABLE "Booking" ADD COLUMN "earlyCheckInFee" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Booking" ADD COLUMN "lateCheckOutFee" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Transaction" ADD COLUMN "stayExtra" TEXT;
